//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDetails.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EmployeesPersonalDetailsEntities : DbContext
    {
        public EmployeesPersonalDetailsEntities()
            : base("name=EmployeesPersonalDetailsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<tbl_EmployeeDetails> tbl_EmployeeDetails { get; set; }
    
        public virtual int Demo(Nullable<int> fkid, Nullable<int> age)
        {
            var fkidParameter = fkid.HasValue ?
                new ObjectParameter("fkid", fkid) :
                new ObjectParameter("fkid", typeof(int));
    
            var ageParameter = age.HasValue ?
                new ObjectParameter("age", age) :
                new ObjectParameter("age", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Demo", fkidParameter, ageParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> LoginEmployee(string userID, string pwd)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("Pwd", pwd) :
                new ObjectParameter("Pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("LoginEmployee", userIDParameter, pwdParameter);
        }
    
        public virtual int sp_EmpInsertUpdate(Nullable<int> empID, string employeeName, string phoneNumber, string description, string empRank, string emailID, string userID, string pwd)
        {
            var empIDParameter = empID.HasValue ?
                new ObjectParameter("EmpID", empID) :
                new ObjectParameter("EmpID", typeof(int));
    
            var employeeNameParameter = employeeName != null ?
                new ObjectParameter("EmployeeName", employeeName) :
                new ObjectParameter("EmployeeName", typeof(string));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("PhoneNumber", phoneNumber) :
                new ObjectParameter("PhoneNumber", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var empRankParameter = empRank != null ?
                new ObjectParameter("EmpRank", empRank) :
                new ObjectParameter("EmpRank", typeof(string));
    
            var emailIDParameter = emailID != null ?
                new ObjectParameter("EmailID", emailID) :
                new ObjectParameter("EmailID", typeof(string));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("Pwd", pwd) :
                new ObjectParameter("Pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EmpInsertUpdate", empIDParameter, employeeNameParameter, phoneNumberParameter, descriptionParameter, empRankParameter, emailIDParameter, userIDParameter, pwdParameter);
        }
    
        public virtual int sp_EmployeeDetail(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EmployeeDetail", idParameter);
        }
    
        public virtual ObjectResult<sp_fetchtbl_EmployeeDetails_Result> sp_fetchtbl_EmployeeDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_fetchtbl_EmployeeDetails_Result>("sp_fetchtbl_EmployeeDetails");
        }
    }
}
